### ISSUE TITLE
SAML-proxy configuration: Exception str object has no attribute information

### ISSUE THREAD

**Issue by rhoerbe** [its-dirg/IdProxy#2]
When the browser is redirected from /idpverify to /sso/redirect, it executes handler_provider_request() > redirect() > operation() > do().

The failure is in idproxy/provider/idp/auth/sp.py in line 109:

```
return self._user_info.information(environ, start_response, uid)
```

The problem is, that _user_info is a str containing "SAML", not an object.

**Comment by rhoerbe** [comment]
I submitted a pull request which does work for the SAML proxy configuration (PEFIM profile). I did not consider other configurations.

**Comment by HaToHo** [comment]
I can't replicate the error and I don't find a pull request.

**Comment by rhoerbe** [comment]
Ah, it seems that I did not create a pull request. but there is a commit in my fork:

https://github.com/rhoerbe/IdProxy/commit/6abdd18b1e45e91218e2d91856b3e2aa3ec0e499 https://github.com/rhoerbe/IdProxy/commit/6abdd18b1e45e91218e2d91856b3e2aa3ec0e499

After 6 months I have lost the reasoning of this issue:-( 

May I ask you to scrutinize the assigns to _use_info object to check if there is a plausible type mismatch?

**Comment by HaToHo** [comment]
I have and can't see anything that should be an issue, and I can run the code with your SP setting without getting an error. It can be related to the proxy configuration. This _user_info object will be less complicated when the code is refactored to PefimProxy, since we will drop other authentication methods and then also drop a lot of configuration options. So I see no point in putting more time on this issue before the code is refactored.

**Comment by HaToHo** [comment]
Code has been refactored and this issue is not longer valid. See pefim_proxy project.
