### ISSUE TITLE
SAML/PEFIM proxy config: xsi:instance declaration missing

### ISSUE THREAD

**Issue by rhoerbe** [its-dirg/IdProxy#5]
A response is issued by the IDP, containing attributes using the xsi namespace. The namespace declaration in the response is correct:

```
<?xml version='1.0' encoding='UTF-8'?>
```

<ns0:Response xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ...

When the response arrives at the SP, the xmlns:xsi declaration is missing, leading to an xml parser error:

```
Other error: unbound prefix: line 4, column 2549
```

**Comment by HaToHo** [comment]
I have added a fix (not yet checked in) that works with your service provider. 

In the current solution the encrypted assertion is inserted in a authn response created by the proxy. If not all namespace are included this error can emerge. To get around this problem the authn request is now created with an empty value for each requested value by the SP. In that way a fake assertion is created that will represent what the SP is expecting and then be replaced with the encrypted assertion.

This only works if the IdP behind the proxy is pysaml2. 

To make it work with other IdP's I probably have to use the original XML response from the underlying IdP and replace information about the proxy IdP, remove the certificate and digital signature and replace it with new once. This is a bit more work, so we have to discuss it.

For assertion that is not encrypted the solution is the same if COPY_ASSERTION flag is true. This may not be the best scenario since it is a much better solution to read the parameters and create a new assertion with the new authn request. This is how it works when OPY_ASSERTION flag is false.

**Comment by HaToHo** [comment]
Replaced with issue #8
